#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass
from datetime import datetime
from gql_client.runtime.datetime_utils import DATETIME_FIELD
from gql_client.runtime.graphql_client import GraphqlClient
from gql_client.runtime.reporter import FailedOperationException
from gql import gql
from gql.transport.exceptions import TransportQueryError
from functools import partial
from numbers import Number
from typing import Any, Callable, List, Mapping, Optional, Dict
from time import perf_counter
from dataclasses_json import DataClassJsonMixin

from .property_type import PropertyTypeFragment, QUERY as PropertyTypeFragmentQuery
QUERY: List[str] = PropertyTypeFragmentQuery + ["""
fragment ProjectTypeFragment on ProjectType {
    id
    name
    description
    properties {
      ...PropertyTypeFragment
    }
    workOrders {
        id
        index
        type {
            id
            name
        }
    }
}
"""]

@dataclass
class ProjectTypeFragment(DataClassJsonMixin):
    @dataclass
    class PropertyType(PropertyTypeFragment):
        pass

    @dataclass
    class WorkOrderDefinition(DataClassJsonMixin):
        @dataclass
        class WorkOrderType(DataClassJsonMixin):
            id: str
            name: str

        id: str
        index: Optional[int]
        type: WorkOrderType

    id: str
    name: str
    description: Optional[str]
    properties: List[PropertyType]
    workOrders: List[WorkOrderDefinition]
