
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "20a66725e8d9938cd3f279ee1b3f3c2acfea3b19",
 "version": "1.2.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
