
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-04T11:36:49+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "84a41c6086f60e6fea55d6fe5fc11d72fa017430",
 "version": "1.2.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
