
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-30T17:55:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8173ae1be73fa301b1d866d8486361dfb9955575",
 "version": "2020.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
