
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-05T15:30:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "13b891a7149750fe9985f496b0019bce326244e0",
 "version": "0.4.0b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
