# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_bye": "00_core.ipynb",
         "optimize_bayes_param": "01_bayes_opt.ipynb",
         "ReadTabBatchIdentity": "02_tab_ae.ipynb",
         "TabularPandasIdentity": "02_tab_ae.ipynb",
         "TabDataLoaderIdentity": "02_tab_ae.ipynb",
         "RecreatedLoss": "02_tab_ae.ipynb",
         "BatchSwapNoise": "02_tab_ae.ipynb",
         "TabularAE": "02_tab_ae.ipynb",
         "HyperparamsGenerator": "03_param_finetune.ipynb",
         "XgboostParamGenerator": "03_param_finetune.ipynb",
         "LgbmParamGenerator": "03_param_finetune.ipynb",
         "CatParamGenerator": "03_param_finetune.ipynb",
         "RFParamGenerator": "03_param_finetune.ipynb",
         "ModelIterator": "04_model_zoo.ipynb"}

modules = ["core.py",
           "bayes_opt.py",
           "tab_ae.py",
           "params.py",
           "model_iterator.py"]

doc_url = "https://DavidykZhao.github.io/Yikai_helper_funcs/"

git_url = "https://github.com/DavidykZhao/Yikai_helper_funcs/tree/master/"

def custom_doc_links(name): return None
