# Generated by Django 3.0.2 on 2020-01-13 12:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('service_name', models.CharField(max_length=45)),
                ('service_guid', models.CharField(default=uuid.uuid4, max_length=45)),
                ('service_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('service_id', models.PositiveSmallIntegerField()),
                ('service_url', models.URLField(blank=True, null=True)),
                ('api_version', models.CharField(blank=True, max_length=10, null=True)),
                ('service_token_url', models.CharField(default='/users/token/', max_length=50)),
                ('service_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
