class MyOperatorException(Exception):
    def __init__(self, message: str) -> None: ...
    def set_message(self, message: str) -> str: ...
    def get_message(self) -> str: ...

def factory_operator(Left: type, Right: type, Output: type) -> type: ...
