# Generated by Django 2.2.13 on 2020-11-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pathfinder_statcrunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='statistics',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
