
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-02T20:19:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "70c36bd65418e7b2a256c7f1da1ed0b4872a7274",
 "version": "0.19.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
