
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-06T16:58:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e366fe2efee8a40b1fab84000ba256bd71021bc",
 "version": "0.8.221"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
