
class WFObjCode:
    '''
    @summary: Workfront object codes
    '''
    project = 'PROJ'
    task = 'TASK'
    templat_task = 'TTSK'
    templat_project = 'TMPL'
    program = 'PRGM'
    portfolio = 'PORT'
    issue = 'optask'
    team = 'TEAM'
    hour = 'hour'
    timesheet = 'tshet'
    user = 'USER'
    assignment = 'assgn'
    user_pref = 'userpf'
    category = 'CTGY'
    category_parameter = 'CTGYPA'
    parameter = 'PARAM'
    parameter_group = 'pgrp'
    parameter_option = 'POPT'
    parameter_value = 'pval'
    role = 'ROLE'
    group = 'group'
    note = 'note'
    document = 'docu'
    document_version = 'docv'
    expense = 'expns'
    custom_enum = 'custem'
