
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-06T14:15:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9998443ccaa45b875ea80da86ac7cfd8e66f161",
 "version": "0.1.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
