# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_domain.events.ipynb (unless otherwise specified).

__all__ = ['__all__', 'Event']

# Cell
#export
from dataclasses import dataclass

# Cell
__all__=['Event']

# Cell
class Event:
    pass