
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-02T14:14:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c974fff00b3b15e802437a076c459bef58b1f67",
 "version": "0.24.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
