#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['b8']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['b8 = b8.app:main']}

setup(name='b8',
      version='0.1.1',
      description='b8, Bominade Ultralight NeoVim-based IDE',
      author='Ali Afshar',
      author_email='aafshar@gmail.com',
      url='https://gitlab.com/afshar-oss/b8',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
      python_requires='>=3.5',
     )
