
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-08T13:15:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e17182c6b7028d61a5e4be1579df63a45f633ec",
 "version": "1.0.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
