
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-02T13:06:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "57393b45aa175d24860aa2d3ae01524d9d91fe52",
 "version": "0.0.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
