# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-03 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xyz_util.modelutils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, verbose_name=b'\xe7\xb1\xbb\xe5\x88\xab')),
                ('name', models.CharField(max_length=256, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'\xe7\x9b\xae\xe6\xa0\x87\xe7\xbc\x96\xe5\x8f\xb7')),
                ('content', xyz_util.modelutils.JSONField(default={}, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u5f85\u51b3'), (1, '\u901a\u8fc7'), (2, '\u62d2\u7edd')], default=0, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('reply', models.CharField(blank=True, default=b'', max_length=256, verbose_name=b'\xe7\xad\x94\xe5\xa4\x8d')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifies_operated', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\xae\xa1\xe6\xa0\xb8\xe5\x91\x98')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name=b'\xe7\x9b\xae\xe6\xa0\x87')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifies', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'ordering': ('-create_time',),
                'verbose_name': '\u5ba1\u6838',
                'verbose_name_plural': '\u5ba1\u6838',
            },
        ),
    ]
