
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-07T02:42:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee2adf0068a5fc5fa2c83043d1db31c2df47ed1b",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
