# Generated by Django 2.2.13 on 2020-11-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pathfinder_statcrunch', '0002_auto_20201102_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='statistics',
            field=models.TextField(blank=True, default='{"characters": {}, "corporations": {}}', editable=False, null=True),
        ),
    ]
