# Generated by Django 3.1.1 on 2020-09-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hydra', 'unaccent_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('route', models.CharField(max_length=512, unique=True, verbose_name='ruta')),
                ('icon_class', models.CharField(blank=True, max_length=128, null=True, verbose_name='clase css del ícono')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='secuencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo?')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='modelo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='hydra.menu', verbose_name='menú padre')),
            ],
            options={
                'ordering': ('route', 'sequence'),
            },
        ),
    ]
