
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-05T15:12:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "dafdb2e21242337527a2fd91a8e358f6a37a564c",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
