
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-01T14:51:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "67479b38c5644021170e40aa8cb8a667d6710132",
 "version": "2020.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
