# Generated by Django 3.0.6 on 2020-10-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakemoneyd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('code',), 'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
    ]
