#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass
from datetime import datetime
from functools import partial
from gql_client.runtime.datetime_utils import DATETIME_FIELD
from numbers import Number
from typing import Any, Callable, List, Mapping, Optional

from dataclasses_json import DataClassJsonMixin

from gql_client.runtime.enum_utils import enum_field
from ..enum.service_status import ServiceStatus

from ..input.property_input import PropertyInput
@dataclass
class ServiceCreateData(DataClassJsonMixin):
    name: str
    serviceTypeId: str
    upstreamServiceIds: List[str]
    status: ServiceStatus = enum_field(ServiceStatus)
    externalId: Optional[str] = None
    customerId: Optional[str] = None
    properties: Optional[List[PropertyInput]] = None

