
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-30T08:15:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dd5db22fefc7ebdfc235ec54a060d37023c7a1c",
 "version": "0.19.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
