#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass
from datetime import datetime
from gql_client.runtime.datetime_utils import DATETIME_FIELD
from gql_client.runtime.graphql_client import GraphqlClient
from gql_client.runtime.reporter import FailedOperationException
from gql import gql
from gql.transport.exceptions import TransportQueryError
from functools import partial
from numbers import Number
from typing import Any, Callable, List, Mapping, Optional, Dict
from time import perf_counter
from dataclasses_json import DataClassJsonMixin

from .property import PropertyFragment, QUERY as PropertyFragmentQuery
QUERY: List[str] = PropertyFragmentQuery + ["""
fragment LocationFragment on Location {
  id
  name
  latitude
  longitude
  externalId
  locationType {
    name
  }
  properties {
    ...PropertyFragment
  }
}

"""]

@dataclass
class LocationFragment(DataClassJsonMixin):
    @dataclass
    class LocationType(DataClassJsonMixin):
        name: str

    @dataclass
    class Property(PropertyFragment):
        pass

    id: str
    name: str
    latitude: Number
    longitude: Number
    externalId: Optional[str]
    locationType: LocationType
    properties: List[Property]
