# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envelope.proto',
  package='dsh.messages.common',
  syntax='proto3',
  serialized_options=_b('\n\014dsh.messages'),
  serialized_pb=_b('\n\x0e\x65nvelope.proto\x12\x13\x64sh.messages.common\"P\n\x0bKeyEnvelope\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.dsh.messages.common.KeyHeader\x12\x0b\n\x03key\x18\x02 \x01(\tJ\x04\x08\x03\x10\x04\"w\n\tKeyHeader\x12\x31\n\nidentifier\x18\x01 \x01(\x0b\x32\x1d.dsh.messages.common.Identity\x12\x10\n\x08retained\x18\x02 \x01(\x08\x12%\n\x03qos\x18\x03 \x01(\x0e\x32\x18.dsh.messages.common.QoS\"u\n\x08Identity\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x13\n\tfree_form\x18\x02 \x01(\tH\x00\x12\x0e\n\x04user\x18\x03 \x01(\tH\x00\x12\x10\n\x06\x63lient\x18\x04 \x01(\tH\x00\x12\x15\n\x0b\x61pplication\x18\x05 \x01(\tH\x00\x42\x0b\n\tpublisher\"\x9a\x01\n\x0c\x44\x61taEnvelope\x12\x11\n\x07payload\x18\x01 \x01(\x0cH\x00\x12?\n\x07tracing\x18\x02 \x03(\x0b\x32..dsh.messages.common.DataEnvelope.TracingEntry\x1a.\n\x0cTracingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x06\n\x04kind*$\n\x03QoS\x12\x0f\n\x0b\x42\x45ST_EFFORT\x10\x00\x12\x0c\n\x08RELIABLE\x10\x01\x42\x0e\n\x0c\x64sh.messagesb\x06proto3')
)

_QOS = _descriptor.EnumDescriptor(
  name='QoS',
  full_name='dsh.messages.common.QoS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEST_EFFORT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELIABLE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=518,
  serialized_end=554,
)
_sym_db.RegisterEnumDescriptor(_QOS)

QoS = enum_type_wrapper.EnumTypeWrapper(_QOS)
BEST_EFFORT = 0
RELIABLE = 1



_KEYENVELOPE = _descriptor.Descriptor(
  name='KeyEnvelope',
  full_name='dsh.messages.common.KeyEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='dsh.messages.common.KeyEnvelope.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='dsh.messages.common.KeyEnvelope.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=119,
)


_KEYHEADER = _descriptor.Descriptor(
  name='KeyHeader',
  full_name='dsh.messages.common.KeyHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='dsh.messages.common.KeyHeader.identifier', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retained', full_name='dsh.messages.common.KeyHeader.retained', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qos', full_name='dsh.messages.common.KeyHeader.qos', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=240,
)


_IDENTITY = _descriptor.Descriptor(
  name='Identity',
  full_name='dsh.messages.common.Identity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tenant', full_name='dsh.messages.common.Identity.tenant', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_form', full_name='dsh.messages.common.Identity.free_form', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='dsh.messages.common.Identity.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='dsh.messages.common.Identity.client', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='application', full_name='dsh.messages.common.Identity.application', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='publisher', full_name='dsh.messages.common.Identity.publisher',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=242,
  serialized_end=359,
)


_DATAENVELOPE_TRACINGENTRY = _descriptor.Descriptor(
  name='TracingEntry',
  full_name='dsh.messages.common.DataEnvelope.TracingEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dsh.messages.common.DataEnvelope.TracingEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='dsh.messages.common.DataEnvelope.TracingEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=508,
)

_DATAENVELOPE = _descriptor.Descriptor(
  name='DataEnvelope',
  full_name='dsh.messages.common.DataEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='dsh.messages.common.DataEnvelope.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracing', full_name='dsh.messages.common.DataEnvelope.tracing', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATAENVELOPE_TRACINGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='dsh.messages.common.DataEnvelope.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=362,
  serialized_end=516,
)

_KEYENVELOPE.fields_by_name['header'].message_type = _KEYHEADER
_KEYHEADER.fields_by_name['identifier'].message_type = _IDENTITY
_KEYHEADER.fields_by_name['qos'].enum_type = _QOS
_IDENTITY.oneofs_by_name['publisher'].fields.append(
  _IDENTITY.fields_by_name['free_form'])
_IDENTITY.fields_by_name['free_form'].containing_oneof = _IDENTITY.oneofs_by_name['publisher']
_IDENTITY.oneofs_by_name['publisher'].fields.append(
  _IDENTITY.fields_by_name['user'])
_IDENTITY.fields_by_name['user'].containing_oneof = _IDENTITY.oneofs_by_name['publisher']
_IDENTITY.oneofs_by_name['publisher'].fields.append(
  _IDENTITY.fields_by_name['client'])
_IDENTITY.fields_by_name['client'].containing_oneof = _IDENTITY.oneofs_by_name['publisher']
_IDENTITY.oneofs_by_name['publisher'].fields.append(
  _IDENTITY.fields_by_name['application'])
_IDENTITY.fields_by_name['application'].containing_oneof = _IDENTITY.oneofs_by_name['publisher']
_DATAENVELOPE_TRACINGENTRY.containing_type = _DATAENVELOPE
_DATAENVELOPE.fields_by_name['tracing'].message_type = _DATAENVELOPE_TRACINGENTRY
_DATAENVELOPE.oneofs_by_name['kind'].fields.append(
  _DATAENVELOPE.fields_by_name['payload'])
_DATAENVELOPE.fields_by_name['payload'].containing_oneof = _DATAENVELOPE.oneofs_by_name['kind']
DESCRIPTOR.message_types_by_name['KeyEnvelope'] = _KEYENVELOPE
DESCRIPTOR.message_types_by_name['KeyHeader'] = _KEYHEADER
DESCRIPTOR.message_types_by_name['Identity'] = _IDENTITY
DESCRIPTOR.message_types_by_name['DataEnvelope'] = _DATAENVELOPE
DESCRIPTOR.enum_types_by_name['QoS'] = _QOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyEnvelope = _reflection.GeneratedProtocolMessageType('KeyEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _KEYENVELOPE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:dsh.messages.common.KeyEnvelope)
  ))
_sym_db.RegisterMessage(KeyEnvelope)

KeyHeader = _reflection.GeneratedProtocolMessageType('KeyHeader', (_message.Message,), dict(
  DESCRIPTOR = _KEYHEADER,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:dsh.messages.common.KeyHeader)
  ))
_sym_db.RegisterMessage(KeyHeader)

Identity = _reflection.GeneratedProtocolMessageType('Identity', (_message.Message,), dict(
  DESCRIPTOR = _IDENTITY,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:dsh.messages.common.Identity)
  ))
_sym_db.RegisterMessage(Identity)

DataEnvelope = _reflection.GeneratedProtocolMessageType('DataEnvelope', (_message.Message,), dict(

  TracingEntry = _reflection.GeneratedProtocolMessageType('TracingEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAENVELOPE_TRACINGENTRY,
    __module__ = 'envelope_pb2'
    # @@protoc_insertion_point(class_scope:dsh.messages.common.DataEnvelope.TracingEntry)
    ))
  ,
  DESCRIPTOR = _DATAENVELOPE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:dsh.messages.common.DataEnvelope)
  ))
_sym_db.RegisterMessage(DataEnvelope)
_sym_db.RegisterMessage(DataEnvelope.TracingEntry)


DESCRIPTOR._options = None
_DATAENVELOPE_TRACINGENTRY._options = None
# @@protoc_insertion_point(module_scope)
