
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-08T14:00:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e09f5100a1354935564c0e4ded2b9a30f1d82f6",
 "version": "1.0.3.1b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
