
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-05T08:59:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4f80e5d14bb1b71f6dca984a4cc52d607fa5ebe",
 "version": "0.7.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
