#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['tankobon', 'tankobon.bootstraps']

package_data = \
{'': ['*']}

install_requires = \
['requests>=2.24.0', 'beautifulsoup4>=4.9.1', 'jsonschema>=3.2.0']

entry_points = \
{'console_scripts': ['tankobon = tankobon.cli:main']}

setup(name='tankobon',
      version='1.0.0a1',
      description='Manga browser/downloader.',
      author='Ong Yong Xin',
      author_email='ongyongxin2020+github@gmail.com',
      url='https://github.com/ongyx/tankobon',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
