
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-06T09:34:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ec451ef9ca031ec7a3021aaccab945cd0996e56",
 "version": "1.14.1.post.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
