# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import redrover_api
from redrover_api.api.user_api import UserApi  # noqa: E501
from redrover_api.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = redrover_api.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_org_id_administrator_id_get(self):
        """Test case for api_org_id_administrator_id_get

        """
        pass

    def test_api_org_id_administrator_post(self):
        """Test case for api_org_id_administrator_post

        """
        pass

    def test_api_org_id_employee_id_get(self):
        """Test case for api_org_id_employee_id_get

        """
        pass

    def test_api_org_id_employee_post(self):
        """Test case for api_org_id_employee_post

        """
        pass

    def test_api_org_id_substitute_get(self):
        """Test case for api_org_id_substitute_get

        """
        pass

    def test_api_org_id_substitute_id_get(self):
        """Test case for api_org_id_substitute_id_get

        """
        pass

    def test_api_org_id_substitute_post(self):
        """Test case for api_org_id_substitute_post

        """
        pass

    def test_api_org_id_user_id_delete(self):
        """Test case for api_org_id_user_id_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
