# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import redrover_api
from redrover_api.models.position_accounting_code_dto import PositionAccountingCodeDto  # noqa: E501
from redrover_api.rest import ApiException

class TestPositionAccountingCodeDto(unittest.TestCase):
    """PositionAccountingCodeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PositionAccountingCodeDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = redrover_api.models.position_accounting_code_dto.PositionAccountingCodeDto()  # noqa: E501
        if include_optional :
            return PositionAccountingCodeDto(
                accounting_code_id = 56, 
                allocation = 1.337
            )
        else :
            return PositionAccountingCodeDto(
                accounting_code_id = 56,
                allocation = 1.337,
        )

    def testPositionAccountingCodeDto(self):
        """Test PositionAccountingCodeDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
