# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import redrover_api
from redrover_api.api.sso_api import SsoApi  # noqa: E501
from redrover_api.rest import ApiException


class TestSsoApi(unittest.TestCase):
    """SsoApi unit test stubs"""

    def setUp(self):
        self.api = redrover_api.api.sso_api.SsoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sso_logout_get(self):
        """Test case for sso_logout_get

        """
        pass

    def test_sso_zendesk_get(self):
        """Test case for sso_zendesk_get

        """
        pass

    def test_sso_zendesk_token_get(self):
        """Test case for sso_zendesk_token_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
