# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import redrover_api
from redrover_api.api.connection_api import ConnectionApi  # noqa: E501
from redrover_api.rest import ApiException


class TestConnectionApi(unittest.TestCase):
    """ConnectionApi unit test stubs"""

    def setUp(self):
        self.api = redrover_api.api.connection_api.ConnectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_org_id_connection_id_data_post(self):
        """Test case for api_org_id_connection_id_data_post

        """
        pass

    def test_api_org_id_connection_id_download_get(self):
        """Test case for api_org_id_connection_id_download_get

        """
        pass

    def test_api_org_id_connection_id_download_post(self):
        """Test case for api_org_id_connection_id_download_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
