# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import redrover_api
from redrover_api.models.time_span import TimeSpan  # noqa: E501
from redrover_api.rest import ApiException

class TestTimeSpan(unittest.TestCase):
    """TimeSpan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TimeSpan
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = redrover_api.models.time_span.TimeSpan()  # noqa: E501
        if include_optional :
            return TimeSpan(
                ticks = 56, 
                days = 56, 
                hours = 56, 
                milliseconds = 56, 
                minutes = 56, 
                seconds = 56, 
                total_days = 1.337, 
                total_hours = 1.337, 
                total_milliseconds = 1.337, 
                total_minutes = 1.337, 
                total_seconds = 1.337
            )
        else :
            return TimeSpan(
        )

    def testTimeSpan(self):
        """Test TimeSpan"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
