# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import redrover_api
from redrover_api.models.simple_person import SimplePerson  # noqa: E501
from redrover_api.rest import ApiException

class TestSimplePerson(unittest.TestCase):
    """SimplePerson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SimplePerson
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = redrover_api.models.simple_person.SimplePerson()  # noqa: E501
        if include_optional :
            return SimplePerson(
                id = 56, 
                external_id = '0', 
                first_name = '0', 
                middle_name = '0', 
                last_name = '0', 
                source_organization_id = 56
            )
        else :
            return SimplePerson(
        )

    def testSimplePerson(self):
        """Test SimplePerson"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
