
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-05T13:44:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d5a1775c5b3d64eff70417a9202f02e46c94e4b",
 "version": "0.4.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
