
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-04T14:24:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8183b1d1b86f29d9560facc7b57a90ad90ad7b0",
 "version": "1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
