# SPDX-License-Identifier: gpl-3.0-or-later
# Copyright (C) 2019 michał góral.

WTYPE_KEYS = {
    "{TAB}"       : 'tab',
    "{ENTER}"     : 'return',
    "{UP}"        : 'up',
    "{DOWN}"      : 'down',
    "{LEFT}"      : 'left',
    "{RIGHT}"     : 'right',
    "{INSERT}"    : 'insert',
    "{INS}"       : 'insert',
    "{DELETE}"    : 'delete',
    "{DEL}"       : 'delete',
    "{HOME}"      : 'home',
    "{END}"       : 'end',
    "{PGUP}"      : 'page_up',
    "{PGDN}"      : 'page_down',
    "{SPACE}"     : 'space',
    "{BACKSPACE}" : 'backspace',
    "{BS}"        : 'backspace',
    "{BKSP}"      : 'backspace',
    "{BREAK}"     : 'break',
    "{CAPSLOCK}"  : 'caps_lock',
    "{ESC}"       : 'escape',
    # "{WIN}"       : 'super',      # unsupported
    # "{LWIN}"      : 'super_l',    # unsupported
    # "{RWIN}"      : 'super_r',    # unsupported
    "{NUMLOCK}"   : 'num_lock',
    "{SCROLLLOCK}": 'scroll_lock',
    "{F1}"        : 'f1',
    "{F2}"        : 'f2',
    "{F3}"        : 'f3',
    "{F4}"        : 'f4',
    "{F5}"        : 'f5',
    "{F6}"        : 'f6',
    "{F7}"        : 'f7',
    "{F8}"        : 'f8',
    "{F9}"        : 'f9',
    "{F10}"       : 'f10',
    "{F11}"       : 'f11',
    "{F12}"       : 'f12',
    "{F13}"       : 'f13',
    "{F14}"       : 'f14',
    "{F15}"       : 'f15',
    "{F16}"       : 'f16',
    "{ADD}"       : 'plus',
    "{SUBTRACT}"  : 'minus',
    "{MULTIPLY}"  : 'asterisk',
    "{DIVIDE}"    : 'slash',
    "{NUMPAD0}"   : '0',
    "{NUMPAD1}"   : '1',
    "{NUMPAD2}"   : '2',
    "{NUMPAD3}"   : '3',
    "{NUMPAD4}"   : '4',
    "{NUMPAD5}"   : '5',
    "{NUMPAD6}"   : '6',
    "{NUMPAD7}"   : '7',
    "{NUMPAD8}"   : '8',
    "{NUMPAD9}"   : '9',
}

