# Generated by Django 3.0.6 on 2020-10-30 20:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='fake currency code real currency', max_length=10, unique=True, verbose_name='currency code')),
                ('name', models.CharField(help_text='currency name to be shown as caption', max_length=128, verbose_name='currency name')),
                ('numeric', models.CharField(blank=True, help_text='Currency numeric for real currency. (nullable)', max_length=3, null=True, verbose_name='currency numeric for real currency')),
                ('countries', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Countries the currency is used in', null=True, verbose_name='countries')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'abstract': False,
            },
        ),
    ]
