
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-05T04:26:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "57a19fe4688e3080ad034a31c7c0c70a5aa01204",
 "version": "1.14.1.post.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
