
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-02T09:19:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b28929669523c3ded972d8a6272fd1cef9163a3",
 "version": "2020.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
