# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2019 Michał Góral.

YDOTOOL_KEYS = {
    "{TAB}"       : 'TAB',
    "{ENTER}"     : 'ENTER',
    "{UP}"        : 'UP',
    "{DOWN}"      : 'DOWN',
    "{LEFT}"      : 'LEFT',
    "{RIGHT}"     : 'RIGHT',
    "{INSERT}"    : 'INSERT',
    "{INS}"       : 'INSERT',
    "{DELETE}"    : 'DELETE',
    "{DEL}"       : 'DELETE',
    "{HOME}"      : 'HOME',
    "{END}"       : 'END',
    "{PGUP}"      : 'PAGEUP',
    "{PGDN}"      : 'PAGEDOWN',
    "{SPACE}"     :  ' ',
    "{BACKSPACE}" : 'BACKSPACE',
    "{BS}"        : 'BACKSPACE',
    "{BKSP}"      : 'BACKSPACE',
    "{BREAK}"     : 'BREAK',
    "{CAPSLOCK}"  : 'CAPSLOCK',
    "{ESC}"       : 'ESCAPE',
    # "{WIN}"       : 'Super',      # unsupported
    # "{LWIN}"      : 'Super_L',    # unsupported
    # "{RWIN}"      : 'Super_R',    # unsupported
    "{NUMLOCK}"   : 'NUMLOCK',
    "{SCROLLLOCK}": 'SCROLLLOCK',
    "{F1}"        : 'F1',
    "{F2}"        : 'F2',
    "{F3}"        : 'F3',
    "{F4}"        : 'F4',
    "{F5}"        : 'F5',
    "{F6}"        : 'F6',
    "{F7}"        : 'F7',
    "{F8}"        : 'F8',
    "{F9}"        : 'F9',
    "{F10}"       : 'F10',
    "{F11}"       : 'F11',
    "{F12}"       : 'F12',
    "{F13}"       : 'F13',
    "{F14}"       : 'F14',
    "{F15}"       : 'F15',
    "{F16}"       : 'F16',
    "{ADD}"       : 'KPPLUS',
    "{SUBTRACT}"  : 'KPMINUS',
    "{MULTIPLY}"  : 'KPASTERISK',
    "{DIVIDE}"    : 'KPSLASH',
    "{NUMPAD0}"   : 'KP0',
    "{NUMPAD1}"   : 'KP1',
    "{NUMPAD2}"   : 'KP2',
    "{NUMPAD3}"   : 'KP3',
    "{NUMPAD4}"   : 'KP4',
    "{NUMPAD5}"   : 'KP5',
    "{NUMPAD6}"   : 'KP6',
    "{NUMPAD7}"   : 'KP7',
    "{NUMPAD8}"   : 'KP8',
    "{NUMPAD9}"   : 'KP9',
}
