
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-02T19:42:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "450c15534b5df6eba871624cb69d4b3ca49c6435",
 "version": "0.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
