# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_bye']

# Cell
def say_hello(name):
    return f'hello {name}'

# Cell
def say_bye(name):
    return f'byes {name}'