# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from redrover_api.configuration import Configuration


class StructLayoutAttribute(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'value': 'LayoutKind',
        'type_id': 'object'
    }

    attribute_map = {
        'value': 'value',
        'type_id': 'typeId'
    }

    def __init__(self, value=None, type_id=None, local_vars_configuration=None):  # noqa: E501
        """StructLayoutAttribute - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._value = None
        self._type_id = None
        self.discriminator = None

        if value is not None:
            self.value = value
        self.type_id = type_id

    @property
    def value(self):
        """Gets the value of this StructLayoutAttribute.  # noqa: E501


        :return: The value of this StructLayoutAttribute.  # noqa: E501
        :rtype: LayoutKind
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this StructLayoutAttribute.


        :param value: The value of this StructLayoutAttribute.  # noqa: E501
        :type value: LayoutKind
        """

        self._value = value

    @property
    def type_id(self):
        """Gets the type_id of this StructLayoutAttribute.  # noqa: E501


        :return: The type_id of this StructLayoutAttribute.  # noqa: E501
        :rtype: object
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this StructLayoutAttribute.


        :param type_id: The type_id of this StructLayoutAttribute.  # noqa: E501
        :type type_id: object
        """

        self._type_id = type_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StructLayoutAttribute):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StructLayoutAttribute):
            return True

        return self.to_dict() != other.to_dict()
