# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from redrover_api.configuration import Configuration


class SubstituteAttributeDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'attribute': 'Int32Locator',
        'expires': 'datetime',
        'attribute_id': 'int',
        'skip_concurrency_check': 'bool',
        'provided_properties': 'list[PropertyInfo]'
    }

    attribute_map = {
        'attribute': 'attribute',
        'expires': 'expires',
        'attribute_id': 'attributeId',
        'skip_concurrency_check': 'skipConcurrencyCheck',
        'provided_properties': 'providedProperties'
    }

    def __init__(self, attribute=None, expires=None, attribute_id=None, skip_concurrency_check=None, provided_properties=None, local_vars_configuration=None):  # noqa: E501
        """SubstituteAttributeDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._attribute = None
        self._expires = None
        self._attribute_id = None
        self._skip_concurrency_check = None
        self._provided_properties = None
        self.discriminator = None

        if attribute is not None:
            self.attribute = attribute
        self.expires = expires
        if attribute_id is not None:
            self.attribute_id = attribute_id
        if skip_concurrency_check is not None:
            self.skip_concurrency_check = skip_concurrency_check
        self.provided_properties = provided_properties

    @property
    def attribute(self):
        """Gets the attribute of this SubstituteAttributeDto.  # noqa: E501


        :return: The attribute of this SubstituteAttributeDto.  # noqa: E501
        :rtype: Int32Locator
        """
        return self._attribute

    @attribute.setter
    def attribute(self, attribute):
        """Sets the attribute of this SubstituteAttributeDto.


        :param attribute: The attribute of this SubstituteAttributeDto.  # noqa: E501
        :type attribute: Int32Locator
        """

        self._attribute = attribute

    @property
    def expires(self):
        """Gets the expires of this SubstituteAttributeDto.  # noqa: E501


        :return: The expires of this SubstituteAttributeDto.  # noqa: E501
        :rtype: datetime
        """
        return self._expires

    @expires.setter
    def expires(self, expires):
        """Sets the expires of this SubstituteAttributeDto.


        :param expires: The expires of this SubstituteAttributeDto.  # noqa: E501
        :type expires: datetime
        """

        self._expires = expires

    @property
    def attribute_id(self):
        """Gets the attribute_id of this SubstituteAttributeDto.  # noqa: E501


        :return: The attribute_id of this SubstituteAttributeDto.  # noqa: E501
        :rtype: int
        """
        return self._attribute_id

    @attribute_id.setter
    def attribute_id(self, attribute_id):
        """Sets the attribute_id of this SubstituteAttributeDto.


        :param attribute_id: The attribute_id of this SubstituteAttributeDto.  # noqa: E501
        :type attribute_id: int
        """

        self._attribute_id = attribute_id

    @property
    def skip_concurrency_check(self):
        """Gets the skip_concurrency_check of this SubstituteAttributeDto.  # noqa: E501


        :return: The skip_concurrency_check of this SubstituteAttributeDto.  # noqa: E501
        :rtype: bool
        """
        return self._skip_concurrency_check

    @skip_concurrency_check.setter
    def skip_concurrency_check(self, skip_concurrency_check):
        """Sets the skip_concurrency_check of this SubstituteAttributeDto.


        :param skip_concurrency_check: The skip_concurrency_check of this SubstituteAttributeDto.  # noqa: E501
        :type skip_concurrency_check: bool
        """

        self._skip_concurrency_check = skip_concurrency_check

    @property
    def provided_properties(self):
        """Gets the provided_properties of this SubstituteAttributeDto.  # noqa: E501


        :return: The provided_properties of this SubstituteAttributeDto.  # noqa: E501
        :rtype: list[PropertyInfo]
        """
        return self._provided_properties

    @provided_properties.setter
    def provided_properties(self, provided_properties):
        """Sets the provided_properties of this SubstituteAttributeDto.


        :param provided_properties: The provided_properties of this SubstituteAttributeDto.  # noqa: E501
        :type provided_properties: list[PropertyInfo]
        """

        self._provided_properties = provided_properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubstituteAttributeDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SubstituteAttributeDto):
            return True

        return self.to_dict() != other.to_dict()
