
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-02T13:42:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "51faa62f7fd54cdb3519c163b82c467540c7414b",
 "version": "1.13.0.post.dev211"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
