#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['aql', 'aql.engines', 'aql.tests', 'aql.tests.engines']

package_data = \
{'': ['*']}

install_requires = \
['attrs']

extras_require = \
{'all': ['aiomysql', 'aiosqlite'],
 'mysql': ['aiomysql'],
 'sqlite': ['aiosqlite']}

setup(name='aql',
      version='0.4.1',
      description='asyncio db query generator',
      author='John Reese',
      author_email='john@noswap.com',
      url='https://github.com/omnilib/aql',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
