from .endpoints.activities import Activities as Activities
from .endpoints.comments import Comments as Comments
from .endpoints.reviews import Reviews as Reviews
from .exceptions import SwarmError as SwarmError, SwarmNotFoundError as SwarmNotFoundError
from collections import namedtuple
from typing import Any

Response = namedtuple('Response', ['status', 'body'])

class Swarm:
    connector: Any = ...
    activities: Any = ...
    reviews: Any = ...
    comments: Any = ...
    def __init__(self, url: str, user: str, password: str) -> None: ...
    def connect(self, host: str, user: str, password: str, version: str) -> Any: ...
    def close(self) -> None: ...
    @property
    def api_version(self) -> float: ...
    def get_version(self) -> dict: ...
