
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-03T16:03:25-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "56a50e2c19579928ff57cecb43079eff74441dfa",
 "version": "1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
