
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-06T19:33:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3a2d3ae473cf3d667888dd7384afbdc5de4bef1",
 "version": "v1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
